<a href="https://colab.research.google.com/github/DanielMasierra/Alura_Store_Latam_Challenge/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [11]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()
tienda2.head()
tienda3.head()
print(tienda.shape,tienda2.shape,tienda3.shape,tienda4.shape)
tienda.columns
tienda.dtypes

(2359, 12) (2359, 12) (2359, 12) (2358, 12)

Producto                   object
Categoría del Producto     object
Precio                    float64
Costo de envío            float64
Fecha de Compra            object
Vendedor                   object
Lugar de Compra            object
Calificación                int64
Método de pago             object
Cantidad de cuotas          int64
lat                       float64
lon                       float64
dtype: object

#1. Análisis de facturación

## 1.1 Suma de ingresos por cada tienda

In [14]:
ingreso_t1 = tienda['Precio'].sum()
ingreso_t2 = tienda2['Precio'].sum()
ingreso_t3 = tienda3['Precio'].sum()
ingreso_t4 = tienda4['Precio'].sum()

ingreso_t1, ingreso_t2, ingreso_t3, ingreso_t4

(np.float64(1150880400.0),
 np.float64(1116343500.0),
 np.float64(1098019600.0),
 np.float64(1038375700.0))

##1.2 Ingresos por tienda

In [17]:
ingresos = pd.Series(
    {"tienda_1": ingreso_t1, "tienda_2": ingreso_t2, "tienda_3": ingreso_t3, "tienda 4": ingreso_t4}
).sort_values(ascending=False)

ingresos

tienda_1    1.150880e+09
tienda_2    1.116344e+09
tienda_3    1.098020e+09
tienda 4    1.038376e+09
dtype: float64

# 2. Ventas por categoría

# 3. Calificación promedio de la tienda

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda